name: Bug report
description: "バグレポートの作成"
title: "タイトル"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: "発生事象"
      description: "発生した不具合の詳細を記載してください（必須）"
      placeholder: "不具合の内容（必須）"
      value: "不具合の内容"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: "再現方法"
      description: "再現性が確立できていたら、再現方法を記載してください（任意）"
      placeholder: "再現方法（任意）"
      value: "不明"
    validations:
      required: false
  - type: dropdown
    id: target
    attributes:
      label: "対象機種"
      description: "どの機種での事象ですか？"
      options:
        - 機種1
        - 機種2
        - 機種3
        - 機種4
      default: 0
    validations:
      required: true
